from __future__ import annotations

# Centralized job-type category definitions with associated keyword dictionaries.
# These lists are consumed by backend.app for both job-description and resume classification.
JOB_TYPE_DEFINITIONS = [
    {
        "id": "software engineering",
        "label": "Software Engineering",
        "keywords": [
            "software engineer",
            "engineer",
            "developer",
            "programmer",
            "software",
            "backend",
            "frontend",
            "full stack",
            "full-stack",
            "platform",
            "site reliability",
            "sre",
            "devops",
            "cloud",
            "api",
            "qa engineer",
            "engineering manager",
            "systems engineer",
            "embedded engineer",
            "embedded",
            "embedded software",
            "firmware",
            "firmware engineer",
            "robotics",
            "robotics engineer",
            "robotics software",
            "autonomous systems",
            "autonomy",
            "control systems",
            "object oriented",
            "object-oriented",
            "uml",
            "mechatronics",
            "mobile engineer",
            "web engineer",
            "data engineer",
            "solutions engineer",
            "security engineer",
            "electronics",
            "rf",
            "circuit",
            "hardware",
        ],
        "skill_keywords": [
            "c",
            "c++",
            "cpp",
            "java",
            "kotlin",
            "swift",
            "objective-c",
            "scala",
            "typescript",
            "javascript",
            "node.js",
            "nodejs",
            "react",
            "angular",
            "vue",
            "go",
            "golang",
            "rust",
            "php",
            ".net",
            "dotnet",
            "spring",
            "django",
            "flask",
            "fastapi",
            "graphql",
            "rest",
            "microservices",
            "aws",
            "azure",
            "gcp",
            "docker",
            "kubernetes",
            "terraform",
            "ansible",
            "jenkins",
            "ci/cd",
            "git",
            "linux",
            "bash",
            "firmware",
            "embedded systems",
            "rtos",
            "fpga",
            "verilog",
            "vhdl",
            "matlab",
            "simulink",
            "altium",
            "arm cortex",
            "cortex-m",
            "stm32",
            "hardware design",
            "uml",
            "ros",
            "robot operating system",
            "gazebo",
            "control theory",
            "control systems",
            "kalman filter",
            "mechatronics",
        ],
    },
    {
        "id": "hardware_engineering",
        "label": "Hardware & Electrical Engineering",
        "keywords": [
            "hardware engineer",
            "electrical engineer",
            "electronics engineer",
            "pcb design",
            "pcb engineer",
            "analog engineer",
            "digital engineer",
            "power systems engineer",
            "power electronics",
            "asic engineer",
            "fpga engineer",
            "hardware validation",
            "electrical design",
            "embedded hardware",
            "rf engineer",
            "signal integrity",
        ],
        "skill_keywords": [
            "altium",
            "kicad",
            "orcad",
            "cadence allegro",
            "ltspice",
            "pspice",
            "vivado",
            "quartus",
            "vhdl",
            "verilog",
            "systemverilog",
            "fpga",
            "asic",
            "rtl",
            "pcb layout",
            "schematic capture",
            "emc",
            "emi",
            "spi",
            "i2c",
            "power integrity",
        ],
    },
    {
        "id": "mechanical_engineering",
        "label": "Mechanical & Manufacturing Engineering",
        "keywords": [
            "mechanical engineer",
            "manufacturing engineer",
            "industrial engineer",
            "mechatronics engineer",
            "process engineer",
            "automation engineer",
            "test engineer",
            "thermal engineer",
            "hvac engineer",
            "tooling engineer",
            "quality engineer",
            "reliability engineer",
            "materials engineer",
        ],
        "skill_keywords": [
            "solidworks",
            "creo",
            "autocad",
            "inventor",
            "catia",
            "ansys",
            "abaqus",
            "gd&t",
            "fea",
            "dfm",
            "dfa",
            "six sigma",
            "lean manufacturing",
            "plc",
            "automation",
            "3d printing",
            "cam",
            "sap erp",
        ],
    },
    {
        "id": "civil_engineering",
        "label": "Civil & Structural Engineering",
        "keywords": [
            "civil engineer",
            "structural engineer",
            "geotechnical engineer",
            "transportation engineer",
            "environmental engineer",
            "construction engineer",
            "water resources engineer",
            "bridge engineer",
            "highway engineer",
            "urban planner",
            "land surveyor",
        ],
        "skill_keywords": [
            "civil 3d",
            "revit",
            "sap2000",
            "staad",
            "etabs",
            "hydrology",
            "stormwater",
            "autocad",
            "gis",
            "microstation",
            "project scheduling",
            "primavera",
            "osha",
            "site planning",
        ],
    },
    {
        "id": "aerospace_engineering",
        "label": "Aerospace & Defense Engineering",
        "keywords": [
            "aerospace engineer",
            "avionics engineer",
            "guidance navigation control",
            "gnc engineer",
            "propulsion engineer",
            "flight dynamics",
            "aerothermal engineer",
            "spacecraft systems",
            "defense engineer",
            "weapons engineer",
            "systems engineer",
        ],
        "skill_keywords": [
            "matlab",
            "simulink",
            "cfd",
            "ansys fluent",
            "patran",
            "nastran",
            "gnc",
            "telemetry",
            "aerospace standards",
            "mil-std",
            "model-based systems engineering",
            "mbse",
            "sysml",
            "labview",
        ],
    },
    {
        "id": "biomedical_engineering",
        "label": "Biomedical & Bioengineering",
        "keywords": [
            "biomedical engineer",
            "bioengineer",
            "medical device engineer",
            "clinical engineer",
            "biomechanical engineer",
            "biotechnology engineer",
            "bioprocess engineer",
            "biosystems engineer",
        ],
        "skill_keywords": [
            "labview",
            "iso 13485",
            "fda",
            "design controls",
            "biocompatibility",
            "gmp",
            "glp",
            "biostatistics",
            "cell culture",
            "bioreactor",
            "medical imaging",
            "cad",
            "solidworks",
            "risk management",
        ],
    },
    {
        "id": "healthcare",
        "label": "Healthcare & Medical",
        "keywords": [
            "physician",
            "doctor",
            "surgeon",
            "medical doctor",
            "md",
            "do",
            "nurse",
            "registered nurse",
            "rn",
            "nurse practitioner",
            "physician assistant",
            "pa",
            "dentist",
            "pharmacist",
            "therapist",
            "physical therapist",
            "occupational therapist",
            "clinical researcher",
            "radiologist",
            "oncologist",
            "cardiologist",
        ],
        "skill_keywords": [
            "patient care",
            "clinical care",
            "diagnosis",
            "treatment planning",
            "emr",
            "ehr",
            "epic",
            "cerner",
            "meditech",
            "clinical trials",
            "hipaa",
            "bls",
            "acls",
            "pharmacology",
            "lab results",
            "medical imaging",
            "telemedicine",
            "care coordination",
        ],
    },
    {
        "id": "data",
        "label": "Data & AI",
        "keywords": [
            "data scientist",
            "data engineer",
            "data analyst",
            "machine learning",
            "ml",
            "artificial intelligence",
            "ai",
            "research scientist",
            "analytics",
            "business intelligence",
            "bi",
            "statistician",
            "data science",
        ],
        "skill_keywords": [
            "python",
            "r",
            "sql",
            "spark",
            "hadoop",
            "pandas",
            "numpy",
            "scikit-learn",
            "sklearn",
            "pytorch",
            "tensorflow",
            "keras",
            "xgboost",
            "dbt",
            "airflow",
            "looker",
            "tableau",
            "power bi",
            "databricks",
            "snowflake",
            "redshift",
            "bigquery",
            "mlops",
            "feature store",
        ],
    },
    {
        "id": "product",
        "label": "Product & Strategy",
        "keywords": [
            "product manager",
            "product owner",
            "pm",
            "product strategy",
            "roadmap",
            "prioritization",
            "prioritize",
            "go-to-market",
            "gtm",
            "product-led",
            "strategy",
        ],
        "skill_keywords": [
            "roadmap",
            "okrs",
            "user research",
            "a/b testing",
            "experimentation",
            "figma",
            "analytics",
            "jira",
            "confluence",
            "product discovery",
        ],
    },
    {
        "id": "design",
        "label": "Design & UX",
        "keywords": [
            "designer",
            "ux",
            "ui",
            "product design",
            "visual designer",
            "interaction designer",
            "creative director",
            "illustrator",
            "ux researcher",
            "design system",
            "brand designer",
        ],
        "skill_keywords": [
            "figma",
            "sketch",
            "adobe xd",
            "photoshop",
            "illustrator",
            "invision",
            "framer",
            "webflow",
            "prototyping",
            "wireframing",
            "user research",
        ],
    },
    {
        "id": "marketing",
        "label": "Marketing & Growth",
        "keywords": [
            "marketing",
            "growth",
            "brand",
            "content",
            "brand communications",
            "marketing communications",
            "demand generation",
            "demand",
            "social media",
            "campaign",
            "pr",
            "community",
        ],
        "skill_keywords": [
            "seo",
            "sem",
            "google ads",
            "facebook ads",
            "hubspot",
            "marketo",
            "pardot",
            "mailchimp",
            "content strategy",
            "copywriting",
            "growth hacking",
            "crm marketing",
            "email marketing",
        ],
    },
    {
        "id": "sales",
        "label": "Sales & Customer Success",
        "keywords": [
            "sales",
            "account executive",
            "business development",
            "bdm",
            "client success",
            "customer success",
            "account manager",
            "revenue",
            "quota",
            "customer support",
        ],
        "skill_keywords": [
            "salesforce",
            "crm",
            "outreach",
            "prospecting",
            "pipeline management",
            "negotiation",
            "cold calling",
            "demo",
        ],
    },
    {
        "id": "operations",
        "label": "Operations & Program",
        "keywords": [
            "operations",
            "ops",
            "program manager",
            "project manager",
            "logistics",
            "process",
            "enablement",
            "delivery",
            "compliance",
            "strategy",
            "strategy operations",
        ],
        "skill_keywords": [
            "process improvement",
            "lean",
            "six sigma",
            "resource planning",
            "jira",
            "asana",
            "trello",
            "monday.com",
            "excel advanced",
            "okrs",
        ],
    },
    {
        "id": "finance",
        "label": "Finance & Analysis",
        "keywords": [
            "finance",
            "financial",
            "accounting",
            "auditor",
            "controller",
            "treasury",
            "budget",
            "investment",
            "fp&a",
            "finance manager",
        ],
        "skill_keywords": [
            "financial modeling",
            "gaap",
            "excel",
            "power bi",
            "sap",
            "oracle",
            "quickbooks",
            "netsuite",
            "valuation",
        ],
    },
    {
        "id": "people",
        "label": "People & HR",
        "keywords": [
            "people",
            "hr",
            "human resources",
            "talent",
            "recruiter",
            "people operations",
            "culture",
            "learning",
        ],
        "skill_keywords": [
            "workday",
            "greenhouse",
            "lever",
            "ats",
            "recruiting",
            "onboarding",
            "employee relations",
            "performance management",
            "talent acquisition",
        ],
    },
    {
        "id": "legal",
        "label": "Legal & Risk",
        "keywords": [
            "legal",
            "compliance",
            "policy",
            "risk",
            "governance",
            "contracts",
            "privacy",
        ],
        "skill_keywords": [
            "contract review",
            "compliance",
            "risk management",
            "policy drafting",
            "litigation",
            "governance",
            "due diligence",
        ],
    },
]

__all__ = ["JOB_TYPE_DEFINITIONS"]
