from __future__ import annotations

# Centralized job-type category definitions with associated keyword dictionaries.
# These lists are consumed by backend.app for both job-description and resume classification.
JOB_TYPE_DEFINITIONS = [
    {
        "id": "software engineering",
        "label": "Software Engineering",
        "keywords": [
            "software engineer",
            "engineer",
            "developer",
            "programmer",
            "software",
            "backend",
            "frontend",
            "full stack",
            "full-stack",
            "platform",
            "site reliability",
            "design systems",
            "accessibility",
            "ux writing",
            "usability testing",
            "visual design",
            "interaction design",
            "information architecture",
            "prototyping tools",
            "component libraries",
            "engineering manager",
            "systems engineer",
            "embedded engineer",
            "embedded",
            "embedded software",
            "firmware",
            "firmware engineer",
            "robotics",
            "robotics engineer",
            "robotics software",
            "autonomous systems",
            "autonomy",
            "control systems",
            "object oriented",
            "object-oriented",
            "uml",
            "mechatronics",
            "mobile engineer",
            "web engineer",
            "data engineer",
            "solutions engineer",
            "security engineer",
            "electronics",
            "rf",
            "circuit",
            "hardware",
        ],
        "skill_keywords": [
            "c",
            "c++",
            "cpp",
            "java",
            "kotlin",
            "swift",
            "objective-c",
            "scala",
            "typescript",
            "javascript",
            "node.js",
            "nodejs",
            "react",
            "angular",
            "vue",
            "go",
            "golang",
            "rust",
            "matlab",
            "nx",
            "proe",
            "cad",
            "simulation",
            "finite element analysis",
            "mechanical design",
            "hydraulics",
            "pneumatics",
            "mechanical systems",
            "cam programming",
            "tooling design",
            "manufacturing processes",
            "geometric dimensioning",
            "failure analysis",
            "fatigue analysis",
            "thermal analysis",
            "materials science",
            "automation systems",
            "robotics integration",
            "aws",
            "azure",
            "gcp",
            "docker",
            "kubernetes",
            "terraform",
            "ansible",
            "jenkins",
            "ci/cd",
                  "kpis",
            "bash",
            "firmware",
            "embedded systems",
            "rtos",
            "fpga",
            "verilog",
            "vhdl",
            "matlab",
            "simulink",
            "altium",
            "arm cortex",
            "ros",
            "robot operating system",
            "gazebo",
            "control theory",
            "control systems",
            "kalman filter",
            "mechatronics",
            "sql",
            "postgresql",
            "mysql",
            "sqlite",
            "mongodb",
            "redis",
            "memcached",
            "elasticsearch",
            "rabbitmq",
            "kafka",
            "grpc",
            "celery",
            "unit testing",
            "pytest",
            "unittest",
            "digital engineer",
            "power systems engineer",
            "power electronics",
            "asic engineer",
            "fpga engineer",
            "hardware validation",
            "electrical design",
            "embedded hardware",
            "rf engineer",
            "signal integrity",
        ],
        "skill_keywords": [
            "altium",
            "kicad",
            "orcad",
            "cadence allegro",
            "ltspice",
            "pspice",
            "vivado",
            "quartus",
            "vhdl",
            "verilog",
            "systemverilog",
            "fpga",
            "asic",
            "rtl",
            "pcb layout",
            "schematic capture",
            "emc",
            "emi",
            "spi",
            "i2c",
            "power integrity",
        ],
    },
    {
        "id": "mechanical_engineering",
        "label": "Mechanical & Manufacturing Engineering",
        "keywords": [
            "mechanical engineer",
            "manufacturing engineer",
            "industrial engineer",
            "mechatronics engineer",
            "process engineer",
            "automation engineer",
            "test engineer",
            "thermal engineer",
            "hvac engineer",
            "tooling engineer",
            "quality engineer",
            "reliability engineer",
            "materials engineer",
        ],
        "skill_keywords": [
            "solidworks",
            "creo",
            "autocad",
            "inventor",
            "catia",
            "ansys",
            "abaqus",
            "gd&t",
            "fea",
            "dfm",
            "dfa",
            "six sigma",
            "lean manufacturing",
            "plc",
            "automation",
            "3d printing",
            "cam",
            "sap erp",
        ],
    },
    {
        "id": "civil_engineering",
        "label": "Civil & Structural Engineering",
        "keywords": [
            "civil engineer",
            "structural engineer",
            "geotechnical engineer",
            "transportation engineer",
            "environmental engineer",
            "construction engineer",
            "water resources engineer",
            "bridge engineer",
            "highway engineer",
            "urban planner",
            "land surveyor",
        ],
        "skill_keywords": [
            "altium",
            "kicad",
            "orcad",
            "cadence allegro",
            "ltspice",
            "pspice",
            "vivado",
            "quartus",
            "vhdl",
            "verilog",
            "systemverilog",
            "fpga",
            "asic",
            "rtl",
            "pcb layout",
            "schematic capture",
            "emc",
            "emi",
            "spi",
            "i2c",
            "power integrity",
            "signal integrity",
            "pcb design",
            "high speed design",
            "analog design",
            "mixed signal",
            "power electronics",
            "test fixtures",
            "boundary scan",
            "jtag",
            "hardware bringup",
            "lab equipment",
            "oscilloscope",
            "logic analyzer",
            "soldering",
            "debugging",
            "test automation",
            "design for test",
            "manufacturing handoff",
            "pcb fabrication",
            "component selection",
            "thermal analysis",
            "emc testing",
            "simulink",
            "cfd",
            "ansys fluent",
            "patran",
            "nastran",
            "gnc",
            "telemetry",
            "aerospace standards",
            "mil-std",
            "model-based systems engineering",
            "mbse",
            "sysml",
            "labview",
        ],
    },
    {
        "id": "biomedical_engineering",
        "label": "Biomedical & Bioengineering",
        "keywords": [
            "biomedical engineer",
            "bioengineer",
            "medical device engineer",
            "clinical engineer",
            "biomechanical engineer",
            "biotechnology engineer",
            "bioprocess engineer",
            "biosystems engineer",
        ],
        "skill_keywords": [
            "labview",
            "iso 13485",
            "fda",
            "design controls",
            "biocompatibility",
            "gmp",
            "glp",
            "biostatistics",
            "cell culture",
            "bioreactor",
            "medical imaging",
            "cad",
            "solidworks",
            "risk management",
        ],
    },
    {
        "id": "healthcare",
        "label": "Healthcare & Medical",
        "keywords": [
            "physician",
            "doctor",
            "surgeon",
            "medical doctor",
            "md",
                "regulatory submissions",
                "clinical validation",
                "medical device design",
                "biomaterials",
                "biosensors",
                "electromechanical",
                "device verification",
                "iso certifications",
                "human factors",
                "usability testing",
                "sterilization",
                "biomechanics",
                "signal processing",
                "embedded firmware",
                "safety risk analysis",
                "rmf",
                "clinical trials design",
                "statistical analysis",
                "regulatory affairs",
            "phlebotomist",
            "lab technician",
            "medical technologist",
            "radiologic technologist",
            "respiratory therapist",
            "pharmacy technician",
            "dentist",
            "pharmacist",
            "therapist",
            "physical therapist",
            "occupational therapist",
            "clinical researcher",
            "radiologist",
            "oncologist",
            "cardiologist",
        ],
        "skill_keywords": [
            "patient care",
            "clinical care",
            "diagnosis",
            "treatment planning",
            "emr",
            "ehr",
            "epic",
            "cerner",
            "meditech",
            "clinical trials",
            "hipaa",
            "bls",
            "acls",
            "pharmacology",
            "lab results",
            "medical imaging",
            "telemedicine",
            "care coordination",
        ],
    },
    {
        "id": "data",
        "label": "Data & AI",
        "keywords": [
            "data scientist",
            "data engineer",
            "data analyst",
            "machine learning",
            "ml",
            "artificial intelligence",
            "ai",
            "research scientist",
            "analytics",
            "business intelligence",
            "bi",
            "statistician",
            "data science",
        ],
        "skill_keywords": [
            "python",
            "r",
            "sql",
            "spark",
            "hadoop",
            "pandas",
            "numpy",
            "scikit-learn",
            "sklearn",
            "pytorch",
            "tensorflow",
            "keras",
            "xgboost",
            "dbt",
            "structural analysis",
            "geotechnical",
            "soil mechanics",
            "surveying",
            "triage",
            "icu",
            "emergency care",
            "patient assessment",
            "medication administration",
            "wound care",
            "clinical documentation",
            "vital signs",
            "medication reconciliation",
            "patient education",
            "infection control",
            "phlebotomy",
            "sterile technique",
            "foundation design",
            "retaining walls",
            "drainage design",
            "traffic engineering",
            "pavement design",
            "soil testing",
            "geotechnical reporting",
            "structural drafting",
            "steel detailing",
            "feature store",
        ],
    },
    {
        "id": "product",
        "label": "Product & Strategy",
        "keywords": [
            "product manager",
            "product owner",
            "pm",
            "product strategy",
            "roadmap",
            "prioritization",
            "prioritize",
            "go-to-market",
            "gtm",
            "product-led",
            "strategy",
        ],
        "skill_keywords": [
            "roadmap",
            "okrs",
            "user research",
            "a/b testing",
            "experimentation",
            "figma",
            "analytics",
            "jira",
            "confluence",
            "product discovery",
        ],
    },
    {
        "id": "design",
        "label": "Design & UX",
        "keywords": [
            "designer",
            "ux",
            "ui",
            "product design",
            "visual designer",
            "interaction designer",
            "creative director",
            "illustrator",
            "ux researcher",
            "design system",
            "brand designer",
        ],
        "skill_keywords": [
            "figma",
            "sketch",
            "adobe xd",
            "photoshop",
            "illustrator",
            "invision",
            "framer",
            "webflow",
            "prototyping",
            "wireframing",
            "user research",
        ],
    },
    {
        "id": "marketing",
        "label": "Marketing & Growth",
        "keywords": [
            "marketing",
            "growth",
            "brand",
            "content",
            "brand communications",
            "marketing communications",
            "demand generation",
            "demand",
            "social media",
            "campaign",
            "pr",
            "community",
        ],
        "skill_keywords": [
            "seo",
            "sem",
            "google ads",
            "facebook ads",
            "hubspot",
            "marketo",
            "pardot",
            "mailchimp",
            "content strategy",
            "copywriting",
            "growth hacking",
            "crm marketing",
            "email marketing",
            "google analytics",
            "social media strategy",
            "content management",
            "marketing analytics",
            "a/b testing",
            "conversion rate optimization",
            "programmatic advertising",
        ],
    },
    {
        "id": "sales",
        "label": "Sales & Customer Success",
        "keywords": [
            "sales",
            "account executive",
            "business development",
            "bdm",
            "client success",
            "customer success",
            "account manager",
            "revenue",
            "quota",
            "customer support",
            "sales operations",
        ],
        "skill_keywords": [
            "salesforce",
            "crm",
            "outreach",
            "prospecting",
            "pipeline management",
            "negotiation",
            "cold calling",
            "demo",
            "closing",
            "quota management",
            "contract negotiation",
            "forecasting",
            "lead generation",
            "customer retention",
            "upselling",
            "cross-selling",
            "sales enablement",
            "sales analytics",
            "territory management",
            "sales presentations",
        ],
    },
    {
        "id": "operations",
        "label": "Operations & Program",
        "keywords": [
            "operations",
            "ops",
            "program manager",
            "project manager",
            "logistics",
            "process",
            "enablement",
            "delivery",
            "compliance",
            "strategy",
            "strategy operations",
        ],
        "skill_keywords": [
            "process improvement",
            "lean",
            "six sigma",
            "resource planning",
            "jira",
            "asana",
            "trello",
            "monday.com",
            "excel advanced",
            "okrs",
        ],
    },
    {
        "id": "finance",
        "label": "Finance & Analysis",
        "keywords": [
            "finance",
            "financial",
            "accounting",
            "auditor",
            "controller",
            "treasury",
            "budget",
            "investment",
            "fp&a",
            "finance manager",
        ],
        "skill_keywords": [
            "financial modeling",
            "gaap",
            "excel",
            "power bi",
            "sap",
            "oracle",
            "quickbooks",
            "netsuite",
            "valuation",
        ],
    },
    {
        "id": "people",
        "label": "People & HR",
        "keywords": [
            "people",
            "hr",
            "human resources",
            "talent",
            "recruiter",
            "people operations",
            "culture",
            "learning",
        ],
        "skill_keywords": [
            "workday",
            "greenhouse",
            "lever",
            "ats",
            "recruiting",
            "onboarding",
            "employee relations",
            "performance management",
            "talent acquisition",
        ],
    },
    {
        "id": "legal",
        "label": "Legal & Risk",
        "keywords": [
            "legal",
            "compliance",
            "policy",
            "risk",
            "governance",
            "contracts",
            "privacy",
        ],
        "skill_keywords": [
            "contract review",
            "compliance",
            "risk management",
            "policy drafting",
            "litigation",
            "governance",
            "due diligence",
        ],
    },
    {
        "id": "security",
        "label": "Security & Privacy",
        "keywords": [
            "security engineer",
            "information security",
            "infosec",
            "application security",
            "appsec",
            "security analyst",
            "penetration tester",
            "pen tester",
            "red team",
            "blue team",
            "cloud security",
            "privacy engineer",
            "compliance",
            "vulnerability",
        ],
        "skill_keywords": [
            "owasp",
            "burp",
            "nmap",
            "wireshark",
            "metasploit",
            "kali",
            "sast",
            "dast",
            "snyk",
            "nessus",
            "iam",
            "mfa",
            "encryption",
            "tls",
            "ssl",
            "kms",
            "cloud security",
            "aws iam",
            "gcp iam",
            "azure ad",
        ],
    },
    {
        "id": "quality_assurance",
        "label": "Quality Assurance & Testing",
        "keywords": [
            "qa engineer",
            "quality assurance",
            "test engineer",
            "automation engineer",
            "sdet",
            "software tester",
            "test automation",
            "manual tester",
            "performance tester",
            "qa lead",
        ],
        "skill_keywords": [
            "selenium",
            "playwright",
            "cypress",
            "pytest",
            "robot framework",
            "junit",
            "testng",
            "mocha",
            "jest",
            "postman",
            "jmeter",
            "load testing",
            "performance testing",
            "bdd",
            "avionics",
            "flight software",
            "attitude control",
            "orbit determination",
            "propulsion",
            "system integration",
            "v&v",
            "rtos",
            "hardware-in-the-loop",
            "aero-structural analysis",
            "trajectory optimization",
            "orbital mechanics",
            "propulsion systems",
            "thermal protection",
            "flight test",
            "avionics integration",
            "sensors",
            "guidance",
            "navigation",
            "control",
            "sre",
            "platform",
            "ci/cd",
            "infrastructure engineer",
            "ops engineer",
            "systems administrator",
            "platform engineer",
        ],
        "skill_keywords": [
            "terraform",
            "ansible",
            "chef",
            "puppet",
            "github actions",
            "circleci",
            "jenkins",
            "argo",
            "flux",
            "prometheus",
            "grafana",
            "observability",
            "otel",
            "elastic",
            "helm",
            "service mesh",
            "istio",
            "consul",
        ],
    },
    {
        "id": "cloud_infrastructure",
        "label": "Cloud Infrastructure & Platform",
        "keywords": [
            "cloud engineer",
            "cloud infrastructure",
            "cloud architect",
            "platform engineer",
            "cloud operations",
            "infrastructure architect",
        ],
        "skill_keywords": [
            "aws",
            "azure",
            "gcp",
            "eks",
            "aks",
            "gke",
            "cloudformation",
            "cdk",
            "cloud run",
            "lambda",
            "functions",
            "vpc",
            "s3",
            "gcs",
            "elb",
            "alb",
            "route53",
        ],
    },
    {
        "id": "research_ml_nlp",
        "label": "Research & ML / NLP",
        "keywords": [
            "research scientist",
            "ml researcher",
            "nlp",
            "natural language processing",
            "deep learning",
            "machine learning research",
            "research engineer",
            "ai researcher",
        ],
        "skill_keywords": [
            "pytorch",
            "tensorflow",
            "transformers",
            "huggingface",
            "spacy",
            "nltk",
            "seq2seq",
            "bert",
            "gpt",
            "attention",
            "distributed training",
            "ray",
            "horovod",
            "mlflow",
            "wandb",
        ],
    },
    {
        "id": "developer_relations",
        "label": "Developer Relations & Documentation",
        "keywords": [
            "developer advocate",
            "developer relations",
            "technical writer",
            "developer evangelist",
            "devrel",
            "documentation",
            "community manager",
        ],
        "skill_keywords": [
            "markdown",
            "docusaurus",
            "sphinx",
            "openapi",
            "swagger",
            "postman",
            "technical writing",
            "content strategy",
        ],
    },
    {
        "id": "academia",
        "label": "Academia & Research",
        "keywords": [
            "professor",
            "lecturer",
            "research assistant",
            "postdoc",
            "phd",
            "academic",
            "teaching assistant",
        ],
        "skill_keywords": [
            "grant writing",
            "teaching",
            "curriculum",
            "peer-reviewed",
            "publishing",
            "latex",
            "rmarkdown",
            "statistical analysis",
        ],
    },
    {
        "id": "executive_management",
        "label": "Executive Leadership & Management",
        "keywords": [
            "ceo",
            "chief executive officer",
            "cto",
            "chief technology officer",
            "cfo",
            "chief financial officer",
            "coo",
            "chief operating officer",
            "vp",
            "vice president",
            "general manager",
            "head of",
            "director",
            "executive director",
            "senior manager",
            "leadership",
            "strategy",
            "business leader",
            "founder",
            "cofounder",
            "owner",
            "managing director",
            "division head",
            "operating officer",
            "board member",
            "board director",
            "company president",
            "enterprise architect",
            "portfolio manager",
            "transformation lead",
        ],
        "skill_keywords": [
            "strategic planning",
            "p&l",
            "profit and loss",
            "budgeting",
            "financial forecasting",
            "stakeholder management",
            "board governance",
            "mergers and acquisitions",
            "change management",
            "organizational design",
            "leadership development",
            "talent strategy",
            "executive communication",
            "negotiation",
            "risk management",
            "business development",
            "go-to-market",
            "okrs",
            "kpi",
            "dashboards",
            "performance management",
            "vendor management",
            "contract negotiation",
            "stakeholder alignment",
            "crisis management",
            "enterprise sales",
            "corporate strategy",
            "stakeholder reporting",
            "leadership coaching",
            "executive recruiting",
        ],
    },
    {
        "id": "supply_chain_logistics",
        "label": "Supply Chain, Procurement & Logistics",
        "keywords": [
            "supply chain",
            "logistics",
            "procurement",
            "buyer",
            "purchasing",
            "supply planner",
            "demand planner",
            "inventory manager",
            "warehouse manager",
            "distribution manager",
            "transportation manager",
            "freight",
            "sourcing",
            "category manager",
            "vendor manager",
            "materials planner",
            "logistics coordinator",
            "operations planner",
            "import export",
            "customs",
            "3pl",
            "last mile",
            "fulfillment",
            "supply chain analyst",
            "supply chain director",
            "procurement specialist",
            "strategic sourcing",
            "supply chain engineer",
            "logistics analyst",
            "warehouse operations",
        ],
        "skill_keywords": [
            "erp",
            "sap",
            "oracle procurement",
            "jda",
            "manhattan",
            "wms",
            "tms",
            "demand planning",
            "forecasting",
            "inventory optimization",
            "lean supply",
            "six sigma",
            "s&op",
            "sales and operations planning",
            "vendor managed inventory",
            "kitting",
            "order management",
            "route optimization",
            "freight forwarding",
            "customs compliance",
            "incoterms",
            "purchase order",
            "rfid",
            "barcode",
            "cold chain",
            "third party logistics",
            "supplier negotiations",
            "cost to serve",
            "lead time reduction",
        ],
    },
    {
        "id": "construction_trades",
        "label": "Construction, Trades & Skilled Labor",
        "keywords": [
            "construction",
            "electrician",
            "plumber",
            "carpenter",
            "foreman",
            "site supervisor",
            "general contractor",
            "project superintendent",
            "mason",
            "welder",
            "pipefitter",
            "hvac technician",
            "mechanic",
            "equipment operator",
            "laborer",
            "roofer",
            "insulator",
            "sheet metal",
            "glazier",
            "concrete",
            "site engineer",
            "civil foreman",
            "construction manager",
            "estimating",
            "quantity surveyor",
            "building inspector",
            "trade apprentice",
            "safety officer",
            "osha",
            "field engineer",
        ],
        "skill_keywords": [
            "blueprint reading",
            "site safety",
            "osha",
            "building codes",
            "foreman leadership",
            "estimating",
            "cost control",
            "project scheduling",
            "critical path method",
            "autocad",
            "revit",
            "construction materials",
            "concrete finishing",
            "welding",
            "rigging",
            "scaffolding",
            "equipment operation",
            "surveying",
            "soil testing",
            "site inspections",
            "quality control",
            "punch lists",
            "subcontractor management",
            "permit management",
            "roofing systems",
            "plumbing systems",
            "electrical systems",
            "hvac systems",
            "safety audits",
        ],
    },
    {
        "id": "hospitality_retail",
        "label": "Hospitality, Travel & Retail",
        "keywords": [
            "hospitality",
            "hotel manager",
            "front desk",
            "concierge",
            "guest services",
            "food and beverage",
            "restaurant manager",
            "chef",
            "cook",
            "service staff",
            "barista",
            "retail",
            "store manager",
            "visual merchandiser",
            "sales associate",
            "inventory clerk",
            "ecommerce",
            "checkout",
            "loss prevention",
            "housekeeping",
            "sommelier",
            "events",
            "banquet",
            "event planner",
            "tour guide",
            "travel agent",
            "customer experience",
            "guest relations",
            "reservation",
            "yield management",
        ],
        "skill_keywords": [
            "pos systems",
            "reservation systems",
            "opera",
            "guest relations",
            "upselling",
            "inventory management",
            "visual merchandising",
            "merchandising",
            "food safety",
            "servsafe",
            "event coordination",
            "table management",
            "housekeeping operations",
            "revenue management",
            "yield management",
            "ecommerce platforms",
            "shopify",
            "magento",
            "customer loyalty",
            "crm",
            "point of sale",
            "staff scheduling",
            "vendor relations",
            "loss prevention",
            "inventory replenishment",
            "visual displays",
            "hospitality training",
            "multilingual support",
            "guest satisfaction",
            "concierge services",
        ],
    },
    {
        "id": "creative_media_entertainment",
        "label": "Creative, Media & Entertainment",
        "keywords": [
            "creative director",
            "art director",
            "graphic designer",
            "illustrator",
            "animator",
            "motion designer",
            "videographer",
            "video editor",
            "producer",
            "editor",
            "copywriter",
            "content creator",
            "social media manager",
            "photographer",
            "cinematographer",
            "sound engineer",
            "composer",
            "performer",
            "actor",
            "musician",
            "production coordinator",
            "broadcast",
            "streaming",
            "podcaster",
            "journalist",
            "media planner",
            "publicist",
            "talent manager",
            "stage manager",
            "props",
        ],
        "skill_keywords": [
            "adobe creative suite",
            "photoshop",
            "illustrator",
            "indesign",
            "after effects",
            "premiere pro",
            "final cut",
            "daVinci resolve",
            "pro tools",
            "ableton",
            "lighting",
            "sound mixing",
            "color grading",
            "storyboarding",
            "camera operation",
            "cinematography",
            "photography",
            "video production",
            "animation",
            "3d modeling",
            "blender",
            "maya",
            "vr",
            "ar",
            "content strategy",
            "social analytics",
            "seo",
            "audience development",
            "media buying",
            "public relations",
        ],
    },
    {
        "id": "environment_sustainability",
        "label": "Environment, Energy & Sustainability",
        "keywords": [
            "environmental scientist",
            "sustainability",
            "renewable energy",
            "solar engineer",
            "wind engineer",
            "climate scientist",
            "environmental consultant",
            "ecologist",
            "conservation",
            "environmental engineer",
            "energy analyst",
            "sustainability manager",
            "carbon",
            "emissions",
            "energy manager",
            "green building",
            "leed",
            "environmental compliance",
            "waste management",
            "recycling",
            "water resources",
            "air quality",
            "environmental policy",
            "climate policy",
            "natural resources",
            "hydrology",
            "environmental impact",
            "ecology",
            "biodiversity",
            "sustainable design",
        ],
        "skill_keywords": [
            "leed",
            "energy modeling",
            "retrofitting",
            "life cycle assessment",
            "lca",
            "carbon accounting",
            "ghg inventory",
            "renewable integration",
            "solar pv",
            "wind turbines",
            "geospatial analysis",
            "gis",
            "environmental permitting",
            "ecological surveys",
            "water treatment",
            "waste management",
            "environmental monitoring",
            "air quality modeling",
            "sustainability reporting",
            "csr",
            "circular economy",
            "energy efficiency",
            "building performance",
            "net zero",
            "climate risk",
            "environmental law",
            "habitat restoration",
            "conservation planning",
            "biodiversity metrics",
            "sustainable supply chains",
        ],
    },
    {
        "id": "real_estate_property",
        "label": "Real Estate, Property & Facilities",
        "keywords": [
            "real estate",
            "property manager",
            "facilities manager",
            "asset manager",
            "leasing agent",
            "broker",
            "real estate agent",
            "property developer",
            "portfolio manager",
            "building manager",
            "facility operations",
            "commercial real estate",
            "residential",
            "property maintenance",
            "site superintendent",
            "estates",
            "tenant relations",
            "lease administration",
            "real estate analyst",
            "valuation",
            "appraisal",
            "property acquisitions",
            "asset disposition",
            "brokerage",
            "zoning",
            "land use",
            "construction management",
            "facility maintenance",
            "building services",
            "estate planning",
        ],
        "skill_keywords": [
            "property management systems",
            "yardi",
            "leasing",
            "tenant relations",
            "facility operations",
            "preventive maintenance",
            "capital projects",
            "lease negotiation",
            "valuation",
            "market analysis",
            "zoning",
            "due diligence",
            "asset management",
            "portfolio optimization",
            "building codes",
            "facility security",
            "energy management",
            "building automation",
            "hvac maintenance",
            "plumbing",
            "electrical maintenance",
            "space planning",
            "occupancy planning",
            "cost estimating",
            "property accounting",
            "capex planning",
            "lease administration",
            "tenant improvement",
            "site acquisition",
            "real estate crm",
        ],
    },
    {
        "id": "customer_support",
        "label": "Customer Support & Success",
        "keywords": [
            "customer support",
            "customer success",
            "support engineer",
            "technical support",
            "help desk",
            "service desk",
            "support specialist",
            "support manager",
            "customer experience",
            "client services",
            "onboarding",
            "implementation",
            "customer advocate",
            "customer operations",
            "support analyst",
            "tier 1",
            "tier 2",
            "tier 3",
            "sla",
            "support coordinator",
            "success manager",
            "renewals",
            "account manager",
            "technical account manager",
            "helpdesk technician",
            "product support",
            "client success",
            "customer retention",
            "churn prevention",
            "support engineer",
        ],
        "skill_keywords": [
            "zendesk",
            "freshdesk",
            "intercom",
            "front",
            "help scout",
            "service now",
            "ticketing",
            "sla management",
            "troubleshooting",
            "root cause analysis",
            "knowledge base",
            "documentation",
            "onboarding",
            "customer training",
            "webinars",
            "product demos",
            "crm",
            "salesforce",
            "renewals",
            "escalation management",
            "incident management",
            "technical troubleshooting",
            "api support",
            "integration support",
            "multilingual support",
            "voice support",
            "chat support",
            "email support",
            "customer health scoring",
            "net promoter score",
        ],
    },
]

__all__ = ["JOB_TYPE_DEFINITIONS"]
